shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - better-sqlite3
  - esbuild
  - sharp
  - simple-git-hooks
  - unrs-resolver
  - vue-demi
